<Project>
	
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' != '.shproj'">
    <NoStdLib>true</NoStdLib>
    <NoConfig>true</NoConfig>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeMetadataVersion>v4.0.30319</RuntimeMetadataVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <Import Project="CoreLib\CoreLib.projitems" Label="Shared" Condition="'$(MSBuildProjectExtension)' == '.csproj'"/>

  <Target Name="CustomizeReferences" BeforeTargets="BeforeCompile" AfterTargets="FindReferenceAssembliesForReferences" Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <ItemGroup>
      <ReferencePathWithRefAssemblies Remove="@(ReferencePathWithRefAssemblies)" />
      <ReferencePath Remove="@(ReferencePath)" />
    </ItemGroup>
  </Target>
	
</Project>
