<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ESP32S3Example\Arduino.cs" Link="Arduino.cs" />
    <Compile Remove="*.xaml.g.cs" />
    <AdditionalFiles Include="*.xaml" />
    <ProjectReference Include="..\LVGLXAMLGenerator\LVGLXAMLGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
